import type { MetadataRoute } from "next";
import { SITE } from "@/lib/seo";

const routes = [
  { path: "", priority: 1.0 },
  { path: "/napoleonic-wars", priority: 1.0 },
  { path: "/battles", priority: 0.9 },
  { path: "/battles/waterloo", priority: 0.95 },
  { path: "/people", priority: 0.9 },
  { path: "/people/napoleon", priority: 0.9 },
  { path: "/people/wellington", priority: 0.9 },
  { path: "/regiments", priority: 0.9 },
  { path: "/regiments/95th-rifles", priority: 0.85 },
  { path: "/stories", priority: 0.8 },
  { path: "/fiction", priority: 0.9 },
  { path: "/fiction/characters", priority: 0.8 },
  { path: "/fiction/recommendations", priority: 0.8 },
  { path: "/resources", priority: 0.8 },
  { path: "/contact", priority: 0.6 },
  { path: "/india/east-india-company", priority: 0.8 },
  { path: "/india", priority: 0.9 },
  { path: "/india/battles/seringapatam", priority: 0.8 },
  { path: "/india/battles/assaye", priority: 0.8 },
  { path: "/india/people/tippu-sultan", priority: 0.8 },
  { path: "/india/people/wellington-in-india", priority: 0.8 },
  { path: "/india/people/richard-wellesley", priority: 0.8 },
  { path: "/india/battles/argaum", priority: 0.8 },
  { path: "/india/battles/gawilghur", priority: 0.8 },
  { path: "/stories/prisoners", priority: 0.8 },
  { path: "/battles/austerlitz", priority: 0.9 },
  { path: "/battles/salamanca", priority: 0.9 },
  { path: "/battles/trafalgar", priority: 0.9 },
  { path: "/stories/purchase-system", priority: 0.8 },
  { path: "/regiments/baker-rifle", priority: 0.8 },
  { path: "/regiments/kings-german-legion", priority: 0.85 },
  { path: "/regiments/52nd-light-infantry", priority: 0.85 },
  { path: "/regiments/scots-greys", priority: 0.85 },
  { path: "/regiments/west-riding", priority: 0.85 },
  { path: "/fiction/characters/sharpe", priority: 0.9 },
  { path: "/fiction/characters/harper", priority: 0.9 },
  { path: "/fiction/characters/hakeswill", priority: 0.85 },
  { path: "/stories/rifleman-harris", priority: 0.85 },
  { path: "/battles/peninsular-war", priority: 0.9 },
  { path: "/battles/hundred-days", priority: 0.9 },
  { path: "/glossary", priority: 0.8 },
  { path: "/battles/badajoz", priority: 0.9 },
  { path: "/battles/corunna", priority: 0.9 },
  { path: "/battles/russian-campaign", priority: 0.9 },
  { path: "/battles/borodino", priority: 0.9 },
  { path: "/battles/vitoria", priority: 0.9 },
  { path: "/fiction/characters/teresa", priority: 0.85 },
  { path: "/fiction/characters/lucille", priority: 0.85 },
  { path: "/stories/life-as-a-soldier", priority: 0.8 },
  { path: "/stories/battlefield-medicine", priority: 0.8 },
] as const;

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return routes.map(({ path, priority }) => ({
    url: `${SITE.baseUrl}${path}`,
    lastModified,
    changeFrequency: "monthly" as const,
    priority,
  }));
}
